/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsultorRouteImport } from './routes/consultor'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApisRouteImport } from './routes/admin.apis'
import { Route as AdminColetasRouteImport } from './routes/admin.coletas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminConsultoresRouteImport } from './routes/admin.consultores'
import { Route as AdminConveniosRouteImport } from './routes/admin.convenios'
import { Route as AdminEditaisRouteImport } from './routes/admin.editais'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminEstadosRouteImport } from './routes/admin.estados'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminFontesRouteImport } from './routes/admin.fontes'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminIndicadoresRouteImport } from './routes/admin.indicadores'
import { Route as AdminInstituicoesRouteImport } from './routes/admin.instituicoes'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminInvestidoresRouteImport } from './routes/admin.investidores'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMunicipiosRouteImport } from './routes/admin.municipios'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminPermissoesRouteImport } from './routes/admin.permissoes'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminRecuperarSenhaRouteImport } from './routes/admin.recuperar-senha'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminScrapersRouteImport } from './routes/admin.scrapers'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ConsultorIndexRouteImport } from './routes/consultor.index'
import { Route as ConsultorAtividadesRouteImport } from './routes/consultor.atividades'
import { Route as ConsultorClientesRouteImport } from './routes/consultor.clientes'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalCandidaturasRouteImport } from './routes/portal.candidaturas'
import { Route as PortalConhecimentoRouteImport } from './routes/portal.conhecimento'
import { Route as PortalEditaisRouteImport } from './routes/portal.editais'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalOnboardingRouteImport } from './routes/portal.onboarding'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalProjetosRouteImport } from './routes/portal.projetos'
import { Route as ConsultorClientesIdRouteImport } from './routes/consultor.clientes.$id'
import { Route as PortalCandidaturasIdRouteImport } from './routes/portal.candidaturas.$id'
import { Route as PortalEditaisIdRouteImport } from './routes/portal.editais.$id'
import { Route as ApiOgEditalIdRouteImport } from './routes/api/og.edital.$id'
import { Route as ApiPublicCronNotificarRouteImport } from './routes/api/public/cron/notificar'
import { Route as ApiPublicCronScrapeRouteImport } from './routes/api/public/cron/scrape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorRoute = ConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisRoute = AdminApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColetasRoute = AdminColetasRouteImport.update({
  id: '/coletas',
  path: '/coletas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultoresRoute = AdminConsultoresRouteImport.update({
  id: '/consultores',
  path: '/consultores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConveniosRoute = AdminConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditaisRoute = AdminEditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstadosRoute = AdminEstadosRouteImport.update({
  id: '/estados',
  path: '/estados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFontesRoute = AdminFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndicadoresRoute = AdminIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstituicoesRoute = AdminInstituicoesRouteImport.update({
  id: '/instituicoes',
  path: '/instituicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvestidoresRoute = AdminInvestidoresRouteImport.update({
  id: '/investidores',
  path: '/investidores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMunicipiosRoute = AdminMunicipiosRouteImport.update({
  id: '/municipios',
  path: '/municipios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissoesRoute = AdminPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecuperarSenhaRoute = AdminRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScrapersRoute = AdminScrapersRouteImport.update({
  id: '/scrapers',
  path: '/scrapers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ConsultorIndexRoute = ConsultorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultorRoute,
} as any)
const ConsultorAtividadesRoute = ConsultorAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => ConsultorRoute,
} as any)
const ConsultorClientesRoute = ConsultorClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => ConsultorRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCandidaturasRoute = PortalCandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalConhecimentoRoute = PortalConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEditaisRoute = PortalEditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOnboardingRoute = PortalOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjetosRoute = PortalProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => PortalRoute,
} as any)
const ConsultorClientesIdRoute = ConsultorClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConsultorClientesRoute,
} as any)
const PortalCandidaturasIdRoute = PortalCandidaturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalCandidaturasRoute,
} as any)
const PortalEditaisIdRoute = PortalEditaisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalEditaisRoute,
} as any)
const ApiOgEditalIdRoute = ApiOgEditalIdRouteImport.update({
  id: '/api/og/edital/$id',
  path: '/api/og/edital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotificarRoute = ApiPublicCronNotificarRouteImport.update({
  id: '/api/public/cron/notificar',
  path: '/api/public/cron/notificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScrapeRoute = ApiPublicCronScrapeRouteImport.update({
  id: '/api/public/cron/scrape',
  path: '/api/public/cron/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultor': typeof ConsultorRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/apis': typeof AdminApisRoute
  '/admin/coletas': typeof AdminColetasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/consultores': typeof AdminConsultoresRoute
  '/admin/convenios': typeof AdminConveniosRoute
  '/admin/editais': typeof AdminEditaisRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/estados': typeof AdminEstadosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/instituicoes': typeof AdminInstituicoesRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/investidores': typeof AdminInvestidoresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/scrapers': typeof AdminScrapersRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/consultor/atividades': typeof ConsultorAtividadesRoute
  '/consultor/clientes': typeof ConsultorClientesRouteWithChildren
  '/portal/candidaturas': typeof PortalCandidaturasRouteWithChildren
  '/portal/conhecimento': typeof PortalConhecimentoRoute
  '/portal/editais': typeof PortalEditaisRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/projetos': typeof PortalProjetosRoute
  '/admin/': typeof AdminIndexRoute
  '/consultor/': typeof ConsultorIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/consultor/clientes/$id': typeof ConsultorClientesIdRoute
  '/portal/candidaturas/$id': typeof PortalCandidaturasIdRoute
  '/portal/editais/$id': typeof PortalEditaisIdRoute
  '/api/og/edital/$id': typeof ApiOgEditalIdRoute
  '/api/public/cron/notificar': typeof ApiPublicCronNotificarRoute
  '/api/public/cron/scrape': typeof ApiPublicCronScrapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/apis': typeof AdminApisRoute
  '/admin/coletas': typeof AdminColetasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/consultores': typeof AdminConsultoresRoute
  '/admin/convenios': typeof AdminConveniosRoute
  '/admin/editais': typeof AdminEditaisRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/estados': typeof AdminEstadosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/instituicoes': typeof AdminInstituicoesRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/investidores': typeof AdminInvestidoresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/scrapers': typeof AdminScrapersRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/consultor/atividades': typeof ConsultorAtividadesRoute
  '/consultor/clientes': typeof ConsultorClientesRouteWithChildren
  '/portal/candidaturas': typeof PortalCandidaturasRouteWithChildren
  '/portal/conhecimento': typeof PortalConhecimentoRoute
  '/portal/editais': typeof PortalEditaisRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/projetos': typeof PortalProjetosRoute
  '/admin': typeof AdminIndexRoute
  '/consultor': typeof ConsultorIndexRoute
  '/portal': typeof PortalIndexRoute
  '/consultor/clientes/$id': typeof ConsultorClientesIdRoute
  '/portal/candidaturas/$id': typeof PortalCandidaturasIdRoute
  '/portal/editais/$id': typeof PortalEditaisIdRoute
  '/api/og/edital/$id': typeof ApiOgEditalIdRoute
  '/api/public/cron/notificar': typeof ApiPublicCronNotificarRoute
  '/api/public/cron/scrape': typeof ApiPublicCronScrapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultor': typeof ConsultorRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/apis': typeof AdminApisRoute
  '/admin/coletas': typeof AdminColetasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/consultores': typeof AdminConsultoresRoute
  '/admin/convenios': typeof AdminConveniosRoute
  '/admin/editais': typeof AdminEditaisRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/estados': typeof AdminEstadosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/instituicoes': typeof AdminInstituicoesRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/investidores': typeof AdminInvestidoresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/scrapers': typeof AdminScrapersRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/consultor/atividades': typeof ConsultorAtividadesRoute
  '/consultor/clientes': typeof ConsultorClientesRouteWithChildren
  '/portal/candidaturas': typeof PortalCandidaturasRouteWithChildren
  '/portal/conhecimento': typeof PortalConhecimentoRoute
  '/portal/editais': typeof PortalEditaisRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/projetos': typeof PortalProjetosRoute
  '/admin/': typeof AdminIndexRoute
  '/consultor/': typeof ConsultorIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/consultor/clientes/$id': typeof ConsultorClientesIdRoute
  '/portal/candidaturas/$id': typeof PortalCandidaturasIdRoute
  '/portal/editais/$id': typeof PortalEditaisIdRoute
  '/api/og/edital/$id': typeof ApiOgEditalIdRoute
  '/api/public/cron/notificar': typeof ApiPublicCronNotificarRoute
  '/api/public/cron/scrape': typeof ApiPublicCronScrapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consultor'
    | '/portal'
    | '/sitemap.xml'
    | '/admin/apis'
    | '/admin/coletas'
    | '/admin/configuracoes'
    | '/admin/consultores'
    | '/admin/convenios'
    | '/admin/editais'
    | '/admin/empresas'
    | '/admin/estados'
    | '/admin/financeiro'
    | '/admin/fontes'
    | '/admin/ia'
    | '/admin/indicadores'
    | '/admin/instituicoes'
    | '/admin/integracoes'
    | '/admin/investidores'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/municipios'
    | '/admin/pagamentos'
    | '/admin/permissoes'
    | '/admin/projetos'
    | '/admin/recuperar-senha'
    | '/admin/relatorios'
    | '/admin/scrapers'
    | '/admin/usuarios'
    | '/consultor/atividades'
    | '/consultor/clientes'
    | '/portal/candidaturas'
    | '/portal/conhecimento'
    | '/portal/editais'
    | '/portal/login'
    | '/portal/onboarding'
    | '/portal/perfil'
    | '/portal/projetos'
    | '/admin/'
    | '/consultor/'
    | '/portal/'
    | '/consultor/clientes/$id'
    | '/portal/candidaturas/$id'
    | '/portal/editais/$id'
    | '/api/og/edital/$id'
    | '/api/public/cron/notificar'
    | '/api/public/cron/scrape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/apis'
    | '/admin/coletas'
    | '/admin/configuracoes'
    | '/admin/consultores'
    | '/admin/convenios'
    | '/admin/editais'
    | '/admin/empresas'
    | '/admin/estados'
    | '/admin/financeiro'
    | '/admin/fontes'
    | '/admin/ia'
    | '/admin/indicadores'
    | '/admin/instituicoes'
    | '/admin/integracoes'
    | '/admin/investidores'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/municipios'
    | '/admin/pagamentos'
    | '/admin/permissoes'
    | '/admin/projetos'
    | '/admin/recuperar-senha'
    | '/admin/relatorios'
    | '/admin/scrapers'
    | '/admin/usuarios'
    | '/consultor/atividades'
    | '/consultor/clientes'
    | '/portal/candidaturas'
    | '/portal/conhecimento'
    | '/portal/editais'
    | '/portal/login'
    | '/portal/onboarding'
    | '/portal/perfil'
    | '/portal/projetos'
    | '/admin'
    | '/consultor'
    | '/portal'
    | '/consultor/clientes/$id'
    | '/portal/candidaturas/$id'
    | '/portal/editais/$id'
    | '/api/og/edital/$id'
    | '/api/public/cron/notificar'
    | '/api/public/cron/scrape'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consultor'
    | '/portal'
    | '/sitemap.xml'
    | '/admin/apis'
    | '/admin/coletas'
    | '/admin/configuracoes'
    | '/admin/consultores'
    | '/admin/convenios'
    | '/admin/editais'
    | '/admin/empresas'
    | '/admin/estados'
    | '/admin/financeiro'
    | '/admin/fontes'
    | '/admin/ia'
    | '/admin/indicadores'
    | '/admin/instituicoes'
    | '/admin/integracoes'
    | '/admin/investidores'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/municipios'
    | '/admin/pagamentos'
    | '/admin/permissoes'
    | '/admin/projetos'
    | '/admin/recuperar-senha'
    | '/admin/relatorios'
    | '/admin/scrapers'
    | '/admin/usuarios'
    | '/consultor/atividades'
    | '/consultor/clientes'
    | '/portal/candidaturas'
    | '/portal/conhecimento'
    | '/portal/editais'
    | '/portal/login'
    | '/portal/onboarding'
    | '/portal/perfil'
    | '/portal/projetos'
    | '/admin/'
    | '/consultor/'
    | '/portal/'
    | '/consultor/clientes/$id'
    | '/portal/candidaturas/$id'
    | '/portal/editais/$id'
    | '/api/og/edital/$id'
    | '/api/public/cron/notificar'
    | '/api/public/cron/scrape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsultorRoute: typeof ConsultorRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgEditalIdRoute: typeof ApiOgEditalIdRoute
  ApiPublicCronNotificarRoute: typeof ApiPublicCronNotificarRoute
  ApiPublicCronScrapeRoute: typeof ApiPublicCronScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor': {
      id: '/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof ConsultorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apis': {
      id: '/admin/apis'
      path: '/apis'
      fullPath: '/admin/apis'
      preLoaderRoute: typeof AdminApisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coletas': {
      id: '/admin/coletas'
      path: '/coletas'
      fullPath: '/admin/coletas'
      preLoaderRoute: typeof AdminColetasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultores': {
      id: '/admin/consultores'
      path: '/consultores'
      fullPath: '/admin/consultores'
      preLoaderRoute: typeof AdminConsultoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/convenios': {
      id: '/admin/convenios'
      path: '/convenios'
      fullPath: '/admin/convenios'
      preLoaderRoute: typeof AdminConveniosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editais': {
      id: '/admin/editais'
      path: '/editais'
      fullPath: '/admin/editais'
      preLoaderRoute: typeof AdminEditaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estados': {
      id: '/admin/estados'
      path: '/estados'
      fullPath: '/admin/estados'
      preLoaderRoute: typeof AdminEstadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fontes': {
      id: '/admin/fontes'
      path: '/fontes'
      fullPath: '/admin/fontes'
      preLoaderRoute: typeof AdminFontesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/indicadores': {
      id: '/admin/indicadores'
      path: '/indicadores'
      fullPath: '/admin/indicadores'
      preLoaderRoute: typeof AdminIndicadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instituicoes': {
      id: '/admin/instituicoes'
      path: '/instituicoes'
      fullPath: '/admin/instituicoes'
      preLoaderRoute: typeof AdminInstituicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/investidores': {
      id: '/admin/investidores'
      path: '/investidores'
      fullPath: '/admin/investidores'
      preLoaderRoute: typeof AdminInvestidoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/municipios': {
      id: '/admin/municipios'
      path: '/municipios'
      fullPath: '/admin/municipios'
      preLoaderRoute: typeof AdminMunicipiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissoes': {
      id: '/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AdminPermissoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recuperar-senha': {
      id: '/admin/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/admin/recuperar-senha'
      preLoaderRoute: typeof AdminRecuperarSenhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scrapers': {
      id: '/admin/scrapers'
      path: '/scrapers'
      fullPath: '/admin/scrapers'
      preLoaderRoute: typeof AdminScrapersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/consultor/': {
      id: '/consultor/'
      path: '/'
      fullPath: '/consultor/'
      preLoaderRoute: typeof ConsultorIndexRouteImport
      parentRoute: typeof ConsultorRoute
    }
    '/consultor/atividades': {
      id: '/consultor/atividades'
      path: '/atividades'
      fullPath: '/consultor/atividades'
      preLoaderRoute: typeof ConsultorAtividadesRouteImport
      parentRoute: typeof ConsultorRoute
    }
    '/consultor/clientes': {
      id: '/consultor/clientes'
      path: '/clientes'
      fullPath: '/consultor/clientes'
      preLoaderRoute: typeof ConsultorClientesRouteImport
      parentRoute: typeof ConsultorRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/candidaturas': {
      id: '/portal/candidaturas'
      path: '/candidaturas'
      fullPath: '/portal/candidaturas'
      preLoaderRoute: typeof PortalCandidaturasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/conhecimento': {
      id: '/portal/conhecimento'
      path: '/conhecimento'
      fullPath: '/portal/conhecimento'
      preLoaderRoute: typeof PortalConhecimentoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/editais': {
      id: '/portal/editais'
      path: '/editais'
      fullPath: '/portal/editais'
      preLoaderRoute: typeof PortalEditaisRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/onboarding': {
      id: '/portal/onboarding'
      path: '/onboarding'
      fullPath: '/portal/onboarding'
      preLoaderRoute: typeof PortalOnboardingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projetos': {
      id: '/portal/projetos'
      path: '/projetos'
      fullPath: '/portal/projetos'
      preLoaderRoute: typeof PortalProjetosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/consultor/clientes/$id': {
      id: '/consultor/clientes/$id'
      path: '/$id'
      fullPath: '/consultor/clientes/$id'
      preLoaderRoute: typeof ConsultorClientesIdRouteImport
      parentRoute: typeof ConsultorClientesRoute
    }
    '/portal/candidaturas/$id': {
      id: '/portal/candidaturas/$id'
      path: '/$id'
      fullPath: '/portal/candidaturas/$id'
      preLoaderRoute: typeof PortalCandidaturasIdRouteImport
      parentRoute: typeof PortalCandidaturasRoute
    }
    '/portal/editais/$id': {
      id: '/portal/editais/$id'
      path: '/$id'
      fullPath: '/portal/editais/$id'
      preLoaderRoute: typeof PortalEditaisIdRouteImport
      parentRoute: typeof PortalEditaisRoute
    }
    '/api/og/edital/$id': {
      id: '/api/og/edital/$id'
      path: '/api/og/edital/$id'
      fullPath: '/api/og/edital/$id'
      preLoaderRoute: typeof ApiOgEditalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notificar': {
      id: '/api/public/cron/notificar'
      path: '/api/public/cron/notificar'
      fullPath: '/api/public/cron/notificar'
      preLoaderRoute: typeof ApiPublicCronNotificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape': {
      id: '/api/public/cron/scrape'
      path: '/api/public/cron/scrape'
      fullPath: '/api/public/cron/scrape'
      preLoaderRoute: typeof ApiPublicCronScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApisRoute: typeof AdminApisRoute
  AdminColetasRoute: typeof AdminColetasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConsultoresRoute: typeof AdminConsultoresRoute
  AdminConveniosRoute: typeof AdminConveniosRoute
  AdminEditaisRoute: typeof AdminEditaisRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminEstadosRoute: typeof AdminEstadosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFontesRoute: typeof AdminFontesRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminIndicadoresRoute: typeof AdminIndicadoresRoute
  AdminInstituicoesRoute: typeof AdminInstituicoesRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminInvestidoresRoute: typeof AdminInvestidoresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMunicipiosRoute: typeof AdminMunicipiosRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPermissoesRoute: typeof AdminPermissoesRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminRecuperarSenhaRoute: typeof AdminRecuperarSenhaRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminScrapersRoute: typeof AdminScrapersRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApisRoute: AdminApisRoute,
  AdminColetasRoute: AdminColetasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConsultoresRoute: AdminConsultoresRoute,
  AdminConveniosRoute: AdminConveniosRoute,
  AdminEditaisRoute: AdminEditaisRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminEstadosRoute: AdminEstadosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFontesRoute: AdminFontesRoute,
  AdminIaRoute: AdminIaRoute,
  AdminIndicadoresRoute: AdminIndicadoresRoute,
  AdminInstituicoesRoute: AdminInstituicoesRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminInvestidoresRoute: AdminInvestidoresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMunicipiosRoute: AdminMunicipiosRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPermissoesRoute: AdminPermissoesRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminRecuperarSenhaRoute: AdminRecuperarSenhaRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminScrapersRoute: AdminScrapersRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ConsultorClientesRouteChildren {
  ConsultorClientesIdRoute: typeof ConsultorClientesIdRoute
}

const ConsultorClientesRouteChildren: ConsultorClientesRouteChildren = {
  ConsultorClientesIdRoute: ConsultorClientesIdRoute,
}

const ConsultorClientesRouteWithChildren =
  ConsultorClientesRoute._addFileChildren(ConsultorClientesRouteChildren)

interface ConsultorRouteChildren {
  ConsultorAtividadesRoute: typeof ConsultorAtividadesRoute
  ConsultorClientesRoute: typeof ConsultorClientesRouteWithChildren
  ConsultorIndexRoute: typeof ConsultorIndexRoute
}

const ConsultorRouteChildren: ConsultorRouteChildren = {
  ConsultorAtividadesRoute: ConsultorAtividadesRoute,
  ConsultorClientesRoute: ConsultorClientesRouteWithChildren,
  ConsultorIndexRoute: ConsultorIndexRoute,
}

const ConsultorRouteWithChildren = ConsultorRoute._addFileChildren(
  ConsultorRouteChildren,
)

interface PortalCandidaturasRouteChildren {
  PortalCandidaturasIdRoute: typeof PortalCandidaturasIdRoute
}

const PortalCandidaturasRouteChildren: PortalCandidaturasRouteChildren = {
  PortalCandidaturasIdRoute: PortalCandidaturasIdRoute,
}

const PortalCandidaturasRouteWithChildren =
  PortalCandidaturasRoute._addFileChildren(PortalCandidaturasRouteChildren)

interface PortalEditaisRouteChildren {
  PortalEditaisIdRoute: typeof PortalEditaisIdRoute
}

const PortalEditaisRouteChildren: PortalEditaisRouteChildren = {
  PortalEditaisIdRoute: PortalEditaisIdRoute,
}

const PortalEditaisRouteWithChildren = PortalEditaisRoute._addFileChildren(
  PortalEditaisRouteChildren,
)

interface PortalRouteChildren {
  PortalCandidaturasRoute: typeof PortalCandidaturasRouteWithChildren
  PortalConhecimentoRoute: typeof PortalConhecimentoRoute
  PortalEditaisRoute: typeof PortalEditaisRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
  PortalOnboardingRoute: typeof PortalOnboardingRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  PortalProjetosRoute: typeof PortalProjetosRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCandidaturasRoute: PortalCandidaturasRouteWithChildren,
  PortalConhecimentoRoute: PortalConhecimentoRoute,
  PortalEditaisRoute: PortalEditaisRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
  PortalOnboardingRoute: PortalOnboardingRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  PortalProjetosRoute: PortalProjetosRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsultorRoute: ConsultorRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgEditalIdRoute: ApiOgEditalIdRoute,
  ApiPublicCronNotificarRoute: ApiPublicCronNotificarRoute,
  ApiPublicCronScrapeRoute: ApiPublicCronScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
